[package]
name = "server_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "1.1.1", features = ["os-poll", "net"] }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
